Handle comments in SQL statements
fox-it/dissect.sql pull request #16
Opened 2023-10-03 22:07 UTC by Schamper

2023-10-04 06:32 UTC, pyrco requested changes

2023-10-04 06:32 UTC, pyrco commented on dissect/sql/utils.py
> +    for i, column_def in enumerate(split_sql_list(column_sql.groups()[0])):
This looks like a debug left-over

2023-10-04 06:32 UTC, pyrco commented on dissect/sql/utils.py
> +                comment = 0
Doesn't this fail when DB or column names have `-` in them?

```
CREATE TABLE foo (
    column-1,
    column-2
)
```

2023-10-04 06:36 UTC, pyrco commented on tests/test_utils.py
> +    ),
Could you add a test-case where DB and/or column names have a dash in them?

`"CREATE TABLE foo (\n    "column-1",\n    "column-2"\n)"`

2023-10-04 21:42 UTC, Schamper commented on dissect/sql/utils.py
> +    for i, column_def in enumerate(split_sql_list(column_sql.groups()[0])):
Oops, correct.

2023-10-09 07:55 UTC, pyrco commented on dissect/sql/utils.py
> +        if not any(quote.values()) and char == "-" and comment != 2:
In the test case example, this would not parse a comment after that line, as the `'` and ``` quotes would still be set to `True` it seems?

2023-10-09 07:57 UTC, pyrco requested changes
see comment

2023-10-12 11:57 UTC, pyrco approved these changes

2023-10-12 12:12 UTC, merged